-- Security alerts table for monitoring
CREATE TABLE IF NOT EXISTS security_alerts (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    alert_type TEXT NOT NULL,
    severity TEXT NOT NULL CHECK (severity IN ('info', 'warning', 'critical')),
    metadata JSONB DEFAULT '{}',
    resolved BOOLEAN DEFAULT false,
    resolved_at TIMESTAMPTZ,
    resolved_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    resolution_notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for security alerts
CREATE INDEX idx_security_alerts_type ON security_alerts(alert_type);
CREATE INDEX idx_security_alerts_severity ON security_alerts(severity);
CREATE INDEX idx_security_alerts_created_at ON security_alerts(created_at);
CREATE INDEX idx_security_alerts_resolved ON security_alerts(resolved);

-- RLS policies
ALTER TABLE security_alerts ENABLE ROW LEVEL SECURITY;

-- Only service role can manage alerts
CREATE POLICY "Service role can manage all alerts" ON security_alerts
    FOR ALL USING (auth.jwt()->>'role' = 'service_role');

-- Admins can view alerts
CREATE POLICY "Admins can view alerts" ON security_alerts
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM auth.users 
            WHERE id = auth.uid() 
            AND raw_user_meta_data->>'is_admin' = 'true'
        )
    );

COMMENT ON TABLE security_alerts IS 'Security monitoring alerts generated by the system';